//RELATED TO PRODUCTS
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST"
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS"
export const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR"
export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS"
export const PRODUCT_FETCH_ERROR = "PRODUCT_FETCH_ERROR"
export const PRODUCT_FETCH_RESET = "PRODUCT_FETCH_RESET"


//CLEARING ANY POST CALL ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS"


//LOGIN RELATED
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"


//REGISTER RELATED
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"


//LOADING USER INTO LOCAL STORAGE
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_ERROR = "LOAD_USER_ERROR"


//LOGOUT CURRENT USER
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"


// CREATE/UPDATE PROFILE
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"


//UPDATE PASSWORD
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"


//FORGOT PASSWORD 
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR"
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET"


//RESET PASSWORD
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET"


//CART RELATED
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART"


//SAVE SHIPPING INFO RELATED
export const SHIPPING_INFORMATION = "SHIPPING_INFORMATION"


//CREATING ORDER RELATED TO PAYMENT GATEWAY
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR"


//GET ALL THE ORDERS OF THE USER(LOGGED IN)
export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST"
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS"
export const GET_MY_ORDERS_ERROR = "GET_MY_ORDERS_ERROR"


//GET ALL THE DETAILS OF AN ORDER
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_ERROR = "GET_ORDER_ERROR"


//RELATED TO CREATING REVIEW
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_ERROR = "CREATE_REVIEW_ERROR"
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET"


//********ADMIN CONSTANTS********


//GET PRODUCTS
export const PRODUCTS_REQUEST_ADMIN = "PRODUCTS_REQUEST_ADMIN"
export const PRODUCTS_SUCCESS_ADMIN = "PRODUCTS_SUCCESS_ADMIN"
export const PRODUCTS_ERROR_ADMIN = "PRODUCTS_ERROR_ADMIN"


//CREATE PRODUCT
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR"
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"


//DELETE PRODUCT
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"


//UPDATE PRODUCT
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"


//ORDERS
export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_ERROR = "GET_ORDERS_ERROR"

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR"
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET"

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR"
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET"


//USERS
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_ERROR = "GET_USERS_ERROR"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"
export const DELETE_USER_RESET = "DELETE_USER_RESET"


export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST"
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS"
export const GET_REVIEWS_ERROR = "GET_REVIEWS_ERROR"
export const GET_REVIEWS_RESET = "GET_REVIEWS_RESET"

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_ERROR = "DELETE_REVIEW_ERROR"
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET"